// ********RoostGPT********
/*
Test generated by RoostGPT for test privateMethodsJava using AI Type Open AI and AI Model gpt-4

1. Test Scenario: Check if the function accepts a valid string as a name.
   Test Steps:
   - Call the `setName()` function with a valid string.
   - Use the `getName()` function to retrieve the name.
   - Verify that the retrieved name equals the name that was set.
   
2. Test Scenario: Check if the function replaces the old name with a new one.
   Test Steps:
   - Set an initial name using the `setName()` function.
   - Set a new name using the `setName()` function.
   - Use the `getName()` function to retrieve the name.
   - Verify that the retrieved name equals the new name that was set.

3. Test Scenario: Check if the function accepts a string with special characters.
   Test Steps:
   - Call the `setName()` function with a string that contains special characters.
   - Use the `getName()` function to retrieve the name.
   - Verify that the retrieved name equals the name that was set with special characters.

4. Test Scenario: Check if the function accepts a string with numbers.
   Test Steps:
   - Call the `setName()` function with a string that contains numbers.
   - Use the `getName()` function to retrieve the name.
   - Verify that the retrieved name equals the name that was set with numbers.

5. Test Scenario: Check if the function accepts an empty string.
   Test Steps:
   - Call the `setName()` function with an empty string.
   - Use the `getName()` function to retrieve the name.
   - Verify that the retrieved name equals the empty string that was set.

6. Test Scenario: Check if the function accepts a string with spaces.
   Test Steps:
   - Call the `setName()` function with a string that contains spaces.
   - Use the `getName()` function to retrieve the name.
   - Verify that the retrieved name equals the name that was set with spaces.

7. Test Scenario: Check if the function accepts a null value.
   Test Steps:
   - Call the `setName()` function with a null value.
   - Use the `getName()` function to retrieve the name.
   - Verify that the retrieved name equals null.
*/

// ********RoostGPT********
package com.houarizegai.calculator.theme.properties;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class Theme_setName_5d23a892d9_Test {
    @Test
    public void testSetName_ValidString() {
        Theme theme = new Theme();
        theme.setName("validName");
        assertEquals("validName", theme.getName());
    }
    
    @Test
    public void testSetName_ReplaceOldName() {
        Theme theme = new Theme();
        theme.setName("oldName");
        theme.setName("newName");
        assertEquals("newName", theme.getName());
    }
    
    @Test
    public void testSetName_SpecialCharacters() {
        Theme theme = new Theme();
        theme.setName("name@#$");
        assertEquals("name@#$", theme.getName());
    }
    
    @Test
    public void testSetName_StringWithNumbers() {
        Theme theme = new Theme();
        theme.setName("name123");
        assertEquals("name123", theme.getName());
    }
    
    @Test
    public void testSetName_EmptyString() {
        Theme theme = new Theme();
        theme.setName("");
        assertEquals("", theme.getName());
    }
    
    @Test
    public void testSetName_StringWithSpaces() {
        Theme theme = new Theme();
        theme.setName("name with spaces");
        assertEquals("name with spaces", theme.getName());
    }
    
    @Test
    public void testSetName_NullValue() {
        Theme theme = new Theme();
        theme.setName(null);
        assertNull(theme.getName());
    }
}
