// ********RoostGPT********
/*
Test generated by RoostGPT for test privateMethodsJava using AI Type Open AI and AI Model gpt-4

1. Test when the name variable is null.
Scenario: Test to check if the function can handle null values.
Steps:
   - Set the name variable as null.
   - Call the getName() function.
   - Verify that the output is null.

2. Test when the name variable is an empty string.
Scenario: Test to check if the function can handle empty strings.
Steps:
   - Set the name variable as an empty string.
   - Call the getName() function.
   - Verify that the output is an empty string.

3. Test when the name variable contains a valid string.
Scenario: Test to check if the function can return a valid name.
Steps:
   - Set the name variable as a valid string.
   - Call the getName() function.
   - Verify that the output is the same string that was set.

4. Test when the name variable contains a string with special characters.
Scenario: Test to check if the function can handle special characters.
Steps:
   - Set the name variable as a string with special characters.
   - Call the getName() function.
   - Verify that the output is the same string that was set.

5. Test when the name variable contains a string with white spaces.
Scenario: Test to check if the function can handle strings with white spaces.
Steps:
   - Set the name variable as a string with white spaces.
   - Call the getName() function.
   - Verify that the output is the same string that was set.

6. Test when the name variable contains a very long string.
Scenario: Test to check if the function can handle long strings.
Steps:
   - Set the name variable as a very long string.
   - Call the getName() function.
   - Verify that the output is the same string that was set.

7. Test when the name variable contains a string with numbers.
Scenario: Test to check if the function can handle strings with numbers.
Steps:
   - Set the name variable as a string with numbers.
   - Call the getName() function.
   - Verify that the output is the same string that was set.
*/

// ********RoostGPT********
package com.houarizegai.calculator.theme.properties;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class Theme_getName_8400ac6fb7_Test {
    
    @Test
    public void testGetNameWhenNameIsNull() {
        Theme theme = new Theme();
        theme.setName(null);
        assertNull(theme.getName());
    }

    @Test
    public void testGetNameWhenNameIsEmpty() {
        Theme theme = new Theme();
        theme.setName("");
        assertEquals("", theme.getName());
    }

    @Test
    public void testGetNameWhenNameIsValid() {
        Theme theme = new Theme();
        theme.setName("Dark");
        assertEquals("Dark", theme.getName());
    }

    @Test
    public void testGetNameWhenNameContainsSpecialCharacters() {
        Theme theme = new Theme();
        theme.setName("@Dark#");
        assertEquals("@Dark#", theme.getName());
    }

    @Test
    public void testGetNameWhenNameContainsWhiteSpaces() {
        Theme theme = new Theme();
        theme.setName("Dark Theme");
        assertEquals("Dark Theme", theme.getName());
    }

    @Test
    public void testGetNameWhenNameIsLong() {
        Theme theme = new Theme();
        String longName = new String(new char[1000]).replace("\0", "a");
        theme.setName(longName);
        assertEquals(longName, theme.getName());
    }

    @Test
    public void testGetNameWhenNameContainsNumbers() {
        Theme theme = new Theme();
        theme.setName("Dark1");
        assertEquals("Dark1", theme.getName());
    }
}
